import * as vscode from 'vscode';

// ── All 2630 Arma SQF commands ────────────────────────────────────────
// Generated from reference.txt — kept in sync by generate-grammar.ps1
// This also serves as the autocomplete word list.

const COMMANDS: string[] = [
    // A
    "abs", "accTime", "acos", "action", "actionIDs", "actionKeys", "actionKeysEx",
    "actionKeysImages", "actionKeysNames", "actionKeysNamesArray", "actionName", "actionNow",
    "actionParams", "activateAddons", "activatedAddons", "activateKey", "activeTitleEffectParams",
    "add3DENConnection", "add3DENEventHandler", "add3DENLayer", "addAction", "addBackpack",
    "addBackpackCargo", "addBackpackCargoGlobal", "addBackpackGlobal", "addBinocularItem",
    "addCamShake", "addCuratorAddons", "addCuratorCameraArea", "addCuratorEditableObjects",
    "addCuratorEditingArea", "addCuratorPoints", "addCuratorSelected", "addEditorObject",
    "addEventHandler", "addForce", "addForceGeneratorRTD", "addGoggles", "addGroupIcon",
    "addHandgunItem", "addHeadgear", "addItem", "addItemCargo", "addItemCargoGlobal",
    "addItemPool", "addItemToBackpack", "addItemToUniform", "addItemToVest", "addLiveStats",
    "addMagazine", "addMagazineAmmoCargo", "addMagazineCargo", "addMagazineCargoGlobal",
    "addMagazineGlobal", "addMagazinePool", "addMagazines", "addMagazinesTurret",
    "addMagazineTurret", "addMenu", "addMenuItem", "addMissionEventHandler", "addMPEventHandler",
    "addMusicEventHandler", "addonFiles", "addOwnedMine", "addPlayerScores",
    "addPrimaryWeaponItem", "addPublicVariableEventHandler", "addRating", "addResources",
    "addScore", "addScoreSide", "addSecondaryWeaponItem", "addSwitchableUnit", "addTeamMember",
    "addToRemainsCollector", "addTorque", "addUniform", "addUserActionEventHandler",
    "addVehicle", "addVest", "addWaypoint", "addWeapon", "addWeaponCargo", "addWeaponCargoGlobal",
    "addWeaponGlobal", "addWeaponItem", "addWeaponPool", "addWeaponTurret",
    "addWeaponWithAttachmentsCargo", "addWeaponWithAttachmentsCargoGlobal", "admin", "agent",
    "agents", "AGLToASL", "aimedAtTarget", "aimPos", "airDensityCurveRTD", "airDensityRTD",
    "airplaneThrottle", "airportSide", "AISFinishHeal", "alive", "all3DENEntities",
    "allActiveTitleEffects", "allAddonsInfo", "allAirports", "allCameras", "allControls",
    "allCurators", "allCutLayers", "allDead", "allDeadMen", "allDiaryRecords",
    "allDiarySubjects", "allDisplays", "allEnv3DSoundSources", "allExtensions", "allGroups",
    "allLODs", "allMapMarkers", "allMines", "allMissionObjects", "allObjects", "allow3DMode",
    "allowCrewInImmobile", "allowCuratorLogicIgnoreAreas", "allowDamage", "allowDammage",
    "allowedService", "allowFileOperations", "allowFleeing", "allowGetIn", "allowService",
    "allowSprint", "allPlayers", "allSimpleObjects", "allSites", "allTurrets", "allUnits",
    "allUnitsUAV", "allUsers", "allVariables", "ambientTemperature", "ammo", "ammoOnPylon",
    "and", "angularVelocity", "angularVelocityModelSpace", "animate", "animateBay",
    "animateDoor", "animatePylon", "animateSource", "animationNames", "animationPhase",
    "animationSourcePhase", "animationState", "apertureParams", "append", "apply", "armoryPoints",
    "arrayIntersect", "asin", "ASLToAGL", "ASLToATL", "assert", "assignAsCargo",
    "assignAsCargoIndex", "assignAsCommander", "assignAsDriver", "assignAsGunner",
    "assignAsTurret", "assignCurator", "assignedCargo", "assignedCommander", "assignedDriver",
    "assignedGroup", "assignedGunner", "assignedItems", "assignedTarget", "assignedTeam",
    "assignedVehicle", "assignedVehicleRole", "assignedVehicles", "assignItem", "assignTeam",
    "assignToAirport", "atan", "atan2", "atg", "ATLToASL", "attachChild", "attachedObject",
    "attachedObjects", "attachedTo", "attachObject", "attachTo", "attackEnabled", "awake",
    // B
    "backpack", "backpackCargo", "backpackContainer", "backpackItems", "backpackMagazines",
    "backpacks", "backpackSpaceFor", "batteryChargeRTD", "behaviour", "benchmark",
    "bezierInterpolation", "binocular", "binocularItems", "binocularMagazine", "blufor",
    "boundingBox", "boundingBoxReal", "boundingCenter", "brakesDisabled", "break", "breakOut",
    "breakTo", "breakWith", "briefingName", "buildingExit", "buildingPos", "buttonAction",
    "buttonSetAction",
    // C
    "cadetMode", "calculatePath", "calculatePlayerVisibilityByFriendly", "call", "callExtension",
    "camCommand", "camCommit", "camCommitPrepared", "camCommitted", "camConstuctionSetParams",
    "camCreate", "camDestroy", "cameraEffect", "cameraEffectEnableHUD", "cameraInterest",
    "cameraOn", "cameraView", "campaignConfigFile", "camPreload", "camPreloaded",
    "camPrepareBank", "camPrepareDir", "camPrepareDive", "camPrepareFocus", "camPrepareFov",
    "camPrepareFovRange", "camPreparePos", "camPrepareRelPos", "camPrepareTarget", "camSetBank",
    "camSetDir", "camSetDive", "camSetFocus", "camSetFov", "camSetFovRange", "camSetPos",
    "camSetRelPos", "camSetTarget", "camTarget", "camUseNVG", "canAdd", "canAddItemToBackpack",
    "canAddItemToUniform", "canAddItemToVest", "cancelSimpleTaskDestination", "canDeployWeapon",
    "canFire", "canMove", "canSlingLoad", "canStand", "canSuspend", "canTriggerDynamicSimulation",
    "canUnloadInCombat", "canVehicleCargo", "captive", "captiveNum", "case", "catch",
    "cbChecked", "cbSetChecked", "ceil", "channelEnabled", "cheatsEnabled", "checkAIFeature",
    "checkVisibility", "childAttached", "civilian", "className", "clear3DENAttribute",
    "clear3DENInventory", "clearAllItemsFromBackpack", "clearBackpackCargo",
    "clearBackpackCargoGlobal", "clearForcesRTD", "clearGroupIcons", "clearItemCargo",
    "clearItemCargoGlobal", "clearItemPool", "clearKillConfirmations", "clearMagazineCargo",
    "clearMagazineCargoGlobal", "clearMagazinePool", "clearOverlay", "clearRadio",
    "clearVehicleInit", "clearWeaponCargo", "clearWeaponCargoGlobal", "clearWeaponPool",
    "clientOwner", "closeDialog", "closeDisplay", "closeOverlay", "collapseObjectTree",
    "collect3DENHistory", "collectiveRTD", "collisionDisabledWith", "combatBehaviour",
    "combatMode", "combatPace", "commandArtilleryFire", "commandChat", "commander",
    "commandFire", "commandFollow", "commandFSM", "commandGetOut", "commandingMenu",
    "commandMove", "commandRadio", "commandStop", "commandSuppressiveFire", "commandTarget",
    "commandWatch", "comment", "commitOverlay", "compatibleItems", "compatibleMagazines",
    "compatibleWeapons", "compile", "compileFinal", "compileScript", "completedFSM",
    "composeText", "configClasses", "configFile", "configHierarchy", "configName", "configNull",
    "configOf", "configProperties", "configSourceAddonList", "configSourceMod",
    "configSourceModList", "confirmSensorTarget", "connectTerminalToUAV", "connectToServer",
    "continueWith", "controlNull", "controlsGroupCtrl", "conversationDisabled",
    "copyFromClipboard", "copyToClipboard", "copyWaypoints", "cos", "count", "countEnemy",
    "countFriendly", "countSide", "countType", "countUnknown", "create3DENComposition",
    "create3DENEntity", "createAgent", "createCenter", "createDialog", "createDiaryLink",
    "createDiaryRecord", "createDiarySubject", "createDisplay", "createGearDialog",
    "createGroup", "createGuardedPoint", "createHashMap", "createHashMapFromArray",
    "createHashMapObject", "createLocation", "createMarker", "createMarkerLocal", "createMenu",
    "createMine", "createMissionDisplay", "createMPCampaignDisplay", "createSimpleObject",
    "createSimpleTask", "createSite", "createSoundSource", "createSoundSourceLocal",
    "createTarget", "createTask", "createTeam", "createTrigger", "createUnit", "createVehicle",
    "createVehicleCrew", "createVehicleLocal", "crew", "ctAddHeader", "ctAddRow", "ctClear",
    "ctCurSel", "ctData", "ctFindHeaderRows", "ctFindRowHeader", "ctHeaderControls",
    "ctHeaderCount", "ctRemoveHeaders", "ctRemoveRows", "ctrlActivate", "ctrlAddEventHandler",
    "ctrlAngle", "ctrlAnimateModel", "ctrlAnimationPhaseModel", "ctrlAt",
    "ctrlAutoScrollDelay", "ctrlAutoScrollRewind", "ctrlAutoScrollSpeed",
    "ctrlBackgroundColor", "ctrlChecked", "ctrlClassName", "ctrlCommit", "ctrlCommitted",
    "ctrlCreate", "ctrlDelete", "ctrlEnable", "ctrlEnabled", "ctrlFade", "ctrlFontHeight",
    "ctrlForegroundColor", "ctrlHTMLLoaded", "ctrlIDC", "ctrlIDD", "ctrlMapAnimAdd",
    "ctrlMapAnimClear", "ctrlMapAnimCommit", "ctrlMapAnimDone", "ctrlMapCursor", "ctrlMapDir",
    "ctrlMapMouseOver", "ctrlMapPosition", "ctrlMapScale", "ctrlMapScreenToWorld",
    "ctrlMapSetPosition", "ctrlMapWorldToScreen", "ctrlModel", "ctrlModelDirAndUp",
    "ctrlModelScale", "ctrlModelVectorSide", "ctrlMousePosition", "ctrlParent",
    "ctrlParentControlsGroup", "ctrlPosition", "ctrlRemoveAllEventHandlers",
    "ctrlRemoveEventHandler", "ctrlScale", "ctrlScrollValues", "ctrlSetActiveColor",
    "ctrlSetAngle", "ctrlSetAutoScrollDelay", "ctrlSetAutoScrollRewind",
    "ctrlSetAutoScrollSpeed", "ctrlSetBackgroundColor", "ctrlSetChecked",
    "ctrlSetDisabledColor", "ctrlSetEventHandler", "ctrlSetFade", "ctrlSetFocus",
    "ctrlSetFont", "ctrlSetFontH1", "ctrlSetFontH1B", "ctrlSetFontH2", "ctrlSetFontH2B",
    "ctrlSetFontH3", "ctrlSetFontH3B", "ctrlSetFontH4", "ctrlSetFontH4B", "ctrlSetFontH5",
    "ctrlSetFontH5B", "ctrlSetFontH6", "ctrlSetFontH6B", "ctrlSetFontHeight",
    "ctrlSetFontHeightH1", "ctrlSetFontHeightH2", "ctrlSetFontHeightH3",
    "ctrlSetFontHeightH4", "ctrlSetFontHeightH5", "ctrlSetFontHeightH6",
    "ctrlSetFontHeightSecondary", "ctrlSetFontP", "ctrlSetFontPB", "ctrlSetFontSecondary",
    "ctrlSetForegroundColor", "ctrlSetModel", "ctrlSetModelDirAndUp", "ctrlSetModelScale",
    "ctrlSetMousePosition", "ctrlSetPixelPrecision", "ctrlSetPosition", "ctrlSetPositionH",
    "ctrlSetPositionW", "ctrlSetPositionX", "ctrlSetPositionY", "ctrlSetScale",
    "ctrlSetScrollValues", "ctrlSetShadow", "ctrlSetStructuredText", "ctrlSetText",
    "ctrlSetTextColor", "ctrlSetTextColorSecondary", "ctrlSetTextSecondary",
    "ctrlSetTextSelection", "ctrlSetTooltip", "ctrlSetTooltipColorBox",
    "ctrlSetTooltipColorShade", "ctrlSetTooltipColorText", "ctrlSetTooltipMaxWidth",
    "ctrlSetURL", "ctrlSetURLOverlayMode", "ctrlShadow", "ctrlShow", "ctrlShown", "ctrlStyle",
    "ctrlText", "ctrlTextColor", "ctrlTextHeight", "ctrlTextSecondary", "ctrlTextSelection",
    "ctrlTextWidth", "ctrlTooltip", "ctrlType", "ctrlURL", "ctrlURLOverlayMode", "ctrlVisible",
    "ctrlWebBrowserAction", "ctRowControls", "ctRowCount", "ctSetCurSel", "ctSetData",
    "ctSetHeaderTemplate", "ctSetRowTemplate", "ctSetValue", "ctValue", "curatorAddons",
    "curatorCamera", "curatorCameraArea", "curatorCameraAreaCeiling", "curatorCoef",
    "curatorEditableObjects", "curatorEditingArea", "curatorEditingAreaType",
    "curatorMouseOver", "curatorPoints", "curatorRegisteredObjects", "curatorSelected",
    "curatorSelectionPreset", "curatorWaypointCost", "current3DENOperation", "currentChannel",
    "currentCommand", "currentMagazine", "currentMagazineDetail", "currentMagazineDetailTurret",
    "currentMagazineTurret", "currentMuzzle", "currentNamespace", "currentPilot",
    "currentTask", "currentTasks", "currentThrowable", "currentVisionMode", "currentWaypoint",
    "currentWeapon", "currentWeaponMode", "currentWeaponTurret", "currentZeroing",
    "cursorObject", "cursorTarget", "customChat", "customRadio", "customWaypointPosition",
    "cutFadeOut", "cutObj", "cutRsc", "cutText",
    // D
    "damage", "date", "dateToNumber", "dayTime", "deActivateKey", "debriefingText", "debugFSM",
    "debugLog", "decayGraphValues", "default", "deg", "delete3DENEntities", "deleteAt",
    "deleteCenter", "deleteCollection", "deleteEditorObject", "deleteGroup",
    "deleteGroupWhenEmpty", "deleteIdentity", "deleteLocation", "deleteMarker",
    "deleteMarkerLocal", "deleteRange", "deleteResources", "deleteSite", "deleteStatus",
    "deleteTarget", "deleteTeam", "deleteVehicle", "deleteVehicleCrew", "deleteWaypoint",
    "detach", "detachChild", "detectedMines", "dialog", "diaryRecordNull",
    "diarySubjectExists", "didJIP", "didJIPOwner", "difficulty", "difficultyEnabled",
    "difficultyEnabledRTD", "difficultyOption", "direction", "directionStabilizationEnabled",
    "directSay", "disableAI", "disableBrakes", "disableCollisionWith", "disableConversation",
    "disableDebriefingStats", "disableMapIndicators", "disableNVGEquipment",
    "disableRemoteSensors", "disableSerialization", "disableTIEquipment",
    "disableUAVConnectability", "disableUserInput", "displayAddEventHandler", "displayChild",
    "displayCtrl", "displayNull", "displayParent", "displayRemoveAllEventHandlers",
    "displayRemoveEventHandler", "displaySetEventHandler", "displayUniqueName",
    "displayUpdate", "dissolveTeam", "distance", "distance2D", "distanceSqr",
    "distributionRegion", "do", "do3DENAction", "doArtilleryFire", "doFire", "doFollow",
    "doFSM", "doGetOut", "doMove", "doorPhase", "doStop", "doSuppressiveFire", "doTarget",
    "doWatch", "drawArrow", "drawEllipse", "drawIcon", "drawIcon3D", "drawLaser", "drawLine",
    "drawLine3D", "drawLink", "drawLocation", "drawPolygon", "drawRectangle", "drawTriangle",
    "drawXPolygon", "driver", "drop", "dynamicSimulationDistance",
    "dynamicSimulationDistanceCoef", "dynamicSimulationEnabled",
    "dynamicSimulationSystemEnabled",
    // E
    "east", "edit3DENMissionAttributes", "editObject", "editorSetEventHandler",
    "effectiveCommander", "echo", "elevatePeriscope", "else", "emptyPositions", "enableAI",
    "enableAIFeature", "enableAimPrecision", "enableAttack", "enableAudioFeature",
    "enableAutoStartUpRTD", "enableAutoTrimRTD", "enableCamShake", "enableCaustics",
    "enableChannel", "enableCollisionWith", "enableCopilot", "enableDebriefingStats",
    "enableDiagLegend", "enableDirectionStabilization", "enableDynamicSimulation",
    "enableDynamicSimulationSystem", "enableEndDialog", "enableEngineArtillery",
    "enableEnvironment", "enableFatigue", "enableFreeLook", "enableGunLights",
    "enableGunStabilization", "enableInfoPanelComponent", "enableIRLasers", "enableMimics",
    "enablePersonTurret", "enableRadio", "enableReload", "enableRopeAttach",
    "enableSatNormalOnDetail", "enableSaving", "enableSentences", "enableSimulation",
    "enableSimulationGlobal", "enableStamina", "enableStressDamage", "enableTeamSwitch",
    "enableTraffic", "enableUAVConnectability", "enableUAVWaypoints", "enableVehicleCargo",
    "enableVehicleSensor", "enableWeaponDisassembly", "endl", "endLoadingScreen",
    "endMission", "enemy", "engineOn", "enginesIsOnRTD", "enginesPowerRTD", "enginesRpmRTD",
    "enginesTorqueRTD", "entities", "environmentEnabled", "environmentVolume",
    "equipmentDisabled", "estimatedEndServerTime", "estimatedTimeLeft", "evalObjectArgument",
    "everyBackpack", "everyContainer", "exec", "execEditorScript", "execFSM", "execVM",
    "exit", "exitWith", "exp", "expectedDestination", "exportJIPMessages",
    "exportLandscapeXYZ", "eyeDirection", "eyePos",
    // F — key commands only (file is huge, rest in code)
    "face", "faction", "fadeEnvironment", "fadeMusic", "fadeRadio", "fadeSound", "fadeSpeech",
    "failMission", "false", "fileExists", "fillWeaponsFromPool", "find", "findAny",
    "findCover", "findDisplay", "findEditorObject", "findEmptyPosition",
    "findEmptyPositionReady", "findIf", "findNearestEnemy", "finishMissionInit", "finite",
    "fire", "fireAtTarget", "firstBackpack", "flag", "flagAnimationPhase", "flagOwner",
    "flagSide", "flagTexture", "flatten", "fleeing", "floor", "flyInHeight", "flyInHeightASL",
    "focusedCtrl", "focusOn", "fog", "fogForecast", "fogParams", "for", "forceAddUniform",
    "forceAtPositionRTD", "forceCadetDifficulty", "forcedMap", "forceEnd",
    "forceFlagTexture", "forceFollowRoad", "forceGeneratorRTD", "forceHitPointsDamageSync",
    "forceMap", "forceRespawn", "forceSpeed", "forceUnicode", "forceWalk", "forceWeaponFire",
    "forceWeatherChange", "forEach", "forEachMember", "forEachMemberAgent",
    "forEachMemberTeam", "forEachReversed", "forgetTarget", "format", "formation",
    "formationDirection", "formationLeader", "formationMembers", "formationPosition",
    "formationTask", "formatText", "formLeader", "freeExtension", "freeLook", "friendly",
    "from", "fromEditor", "fromJSON", "fuel", "fullCrew",
    // G
    "gestureState", "get", "get3DENAttribute", "getAimDirectionAndUp", "getAimingCoef",
    "getAllHitPointsDamage", "getArray", "getAssignedCuratorUnit", "getAttackTarget",
    "getBackpackCargo", "getBleedingRemaining", "getCargoIndex", "getCenterOfMass",
    "getConnectedUAV", "getDammage", "getDir", "getDiverState", "getFatigue", "getFriend",
    "getFSMVariable", "getFuelCargo", "getHit", "getHitPointDamage", "getItemCargo",
    "getMagazineCargo", "getMarkerColor", "getMarkerPos", "getMarkerSize", "getMarkerType",
    "getMass", "getMissionConfig", "getMissionPath", "getModelInfo", "getNumber",
    "getObjectChildren", "getObjectDLC", "getObjectTextures", "getObjectType",
    "getOxygenRemaining", "getPlayerUID", "getPos", "getPosASL", "getPosATL", "getPosWorld",
    "getRelDir", "getRelPos", "getRepairCargo", "getResolution", "getRoadInfo",
    "getShadowDistance", "getSlingLoad", "getSpeed", "getStamina", "getSuppression",
    "getTerrainHeight", "getTerrainHeightASL", "getText", "getTextWidth", "getTowParent",
    "getUnitLoadout", "getVariable", "getVehicleCargo", "getWeaponCargo", "getWeaponSway",
    "getWPPos", "glanceAt", "globalChat", "globalRadio", "goggles", "goto", "group",
    "groupChat", "groupFromNetId", "groupIconSelectable", "groupIconsVisible", "groupId",
    "groupOwner", "groupRadio", "groups", "groupSelectedUnits", "groupSelectUnit", "grpNull",
    "gunner", "gusts",
    // H
    "halt", "handgunItems", "handgunMagazine", "handgunWeapon", "handsHit", "hasInterface",
    "hasPilotCamera", "hasWeapon", "hcAllGroups", "hcLeader", "hcRemoveAllGroups",
    "hcRemoveGroup", "hcSelected", "hcSelectGroup", "hcSetGroup", "hcShowBar", "hcShownBar",
    "headgear", "hiddenActions", "hideActions", "hideBody", "hideObject", "hideObjectGlobal",
    "hideSelection", "hint", "hintC", "hintCadet", "hintSilent", "hmd", "hostMission",
    "htmlLoad", "HUDMovementLevels", "humidity",
    // I
    "if", "ignoreTarget", "image", "import", "importance", "in", "inArea", "inAreaArray",
    "incapacitatedState", "independent", "inflame", "inflamed", "infoPanel",
    "infoPanelComponentEnabled", "infoPanelComponents", "infoPanels",
    "inGameUISetEventHandler", "inheritsFrom", "initAmbientLife", "inPolygon", "inputAction",
    "inRangeOfArtillery", "insert", "insertEditorObject", "insideBuilding", "intersect",
    "is3DEN", "is3DENMultiplayer", "isAbleToBreathe", "isAgent", "isAimPrecisionEnabled",
    "isArray", "isAutoHoverOn", "isAutonomous", "isBleeding", "isBurning", "isClass",
    "isCollisionLightOn", "isCopilotEnabled", "isDamageAllowed", "isDedicated",
    "isDLCAvailable", "isEngineOn", "isEqualTo", "isEqualType", "isEqualTypeAll",
    "isEqualTypeAny", "isEqualTypeArray", "isEqualTypeParams", "isFilePatchingEnabled",
    "isFinal", "isFlashlightOn", "isFlatEmpty", "isForcedWalk", "isFormationLeader",
    "isGameFocused", "isGamePaused", "isGroupDeletedWhenEmpty", "isHidden", "isInRemainsCollector",
    "isIRLaserOn", "isKeyActive", "isKindOf", "isLaserOn", "isLightOn", "isLocalized",
    "isManualFire", "isMarkedForCollection", "isMultiplayer", "isMultiplayerSolo", "isNil",
    "isNull", "isNumber", "isObjectHidden", "isObjectRTD", "isOnRoad", "isPiPEnabled",
    "isPlayer", "isRealTime", "isRemoteExecuted", "isRemoteExecutedJIP", "isSaving",
    "isSensorTargetConfirmed", "isServer", "isShowing3DIcons", "isSimpleObject",
    "isSprintAllowed", "isStaminaEnabled", "isSteamMission", "isSteamOverlayEnabled",
    "isStreamFriendlyUIEnabled", "isStressDamageEnabled", "isText", "isThrowable",
    "isTouchingGround", "isTurnedOut", "isTutHintsEnabled", "isUAVConnectable",
    "isUAVConnected", "isUIContext", "isUniformAllowed", "isVehicleCargo",
    "isVehicleRadarOn", "isVehicleSensorEnabled", "isWalking", "isWeaponDeployed",
    "isWeaponRested", "itemCargo", "items", "itemsWithMagazines",
    // J
    "join", "joinAs", "joinAsSilent", "joinSilent", "joinString",
    // K
    "kbAddDatabase", "kbAddDatabaseTargets", "kbAddTopic", "kbHasTopic", "kbReact",
    "kbRemoveTopic", "kbTell", "kbWasSaid", "keyImage", "keyName", "keys", "kickPlayer",
    "knowsAbout",
    // L
    "land", "landAt", "landResult", "language", "laserTarget", "lbAdd", "lbClear", "lbColor",
    "lbColorRight", "lbCurSel", "lbData", "lbDelete", "lbIsSelected", "lbPicture",
    "lbPictureRight", "lbSelection", "lbSetColor", "lbSetColorRight", "lbSetCurSel",
    "lbSetData", "lbSetPicture", "lbSetPictureColor", "lbSetPictureColorDisabled",
    "lbSetPictureColorSelected", "lbSetPictureRight", "lbSetPictureRightColor",
    "lbSetPictureRightColorDisabled", "lbSetPictureRightColorSelected", "lbSetSelectColor",
    "lbSetSelectColorRight", "lbSetSelected", "lbSetText", "lbSetTextRight", "lbSetTooltip",
    "lbSetValue", "lbSize", "lbSort", "lbSortBy", "lbSortByValue", "lbText", "lbTextRight",
    "lbTooltip", "lbValue", "leader", "leaderboardDeInit", "leaderboardGetRows",
    "leaderboardInit", "leaveVehicle", "libraryCredits", "libraryDisclaimers", "lifeState",
    "lightAttachObject", "lightDetachObject", "lightIsOn", "lightnings", "limitSpeed",
    "linearConversion", "lineBreak", "lineIntersects", "lineIntersectsObjs",
    "lineIntersectsSurfaces", "lineIntersectsWith", "linkItem", "list", "listObjects",
    "listRemoteTargets", "listVehicleSensors", "ln", "lnbAddArray", "lnbAddColumn",
    "lnbAddRow", "lnbClear", "lnbColor", "lnbColorRight", "lnbCurSelRow", "lnbData",
    "lnbDeleteColumn", "lnbDeleteRow", "lnbGetColumnsPosition", "lnbPicture",
    "lnbPictureRight", "lnbSetColor", "lnbSetColorRight", "lnbSetColumnsPos",
    "lnbSetCurSelRow", "lnbSetData", "lnbSetPicture", "lnbSetPictureColor",
    "lnbSetPictureColorRight", "lnbSetPictureColorSelected",
    "lnbSetPictureColorSelectedRight", "lnbSetPictureRight", "lnbSetText",
    "lnbSetTextRight", "lnbSetTooltip", "lnbSetValue", "lnbSize", "lnbSort", "lnbSortBy",
    "lnbSortByValue", "lnbText", "lnbTextRight", "lnbValue", "load", "load3DENScenario",
    "loadAbs", "loadBackpack", "loadConfig", "loadFile", "loadGame", "loadIdentity",
    "loadMagazine", "loadOverlay", "loadStatus", "loadUniform", "loadVest", "local",
    "localize", "localNamespace", "locationNull", "locationPosition", "lock", "lockCameraTo",
    "lockCargo", "lockDriver", "locked", "lockedCameraTo", "lockedCargo", "lockedDriver",
    "lockedInventory", "lockedTurret", "lockIdentity", "lockInventory", "lockTurret",
    "lockWP", "log", "logEntities", "logNetwork", "logNetworkTerminate", "lookAt", "lookAtPos",
    // M
    "magazineCargo", "magazines", "magazinesAllTurrets", "magazinesAmmo",
    "magazinesAmmoCargo", "magazinesAmmoFull", "magazinesDetail", "magazinesDetailBackpack",
    "magazinesDetailUniform", "magazinesDetailVest", "magazinesTurret", "magazineTurretAmmo",
    "mapAnimAdd", "mapAnimClear", "mapAnimCommit", "mapAnimDone", "mapCenterOnCamera",
    "mapGridPosition", "markAsFinishedOnSteam", "markerAlpha", "markerBrush",
    "markerChannel", "markerColor", "markerDir", "markerDrawPriority", "markerPolyline",
    "markerPos", "markerShadow", "markerShape", "markerSize", "markerText", "markerType",
    "matrixMultiply", "matrixTranspose", "max", "maxLoad", "members", "menuAction",
    "menuAdd", "menuChecked", "menuClear", "menuCollapse", "menuData", "menuDelete",
    "menuEnable", "menuEnabled", "menuExpand", "menuHover", "menuPicture", "menuSetAction",
    "menuSetCheck", "menuSetData", "menuSetPicture", "menuSetShortcut", "menuSetText",
    "menuSetURL", "menuSetValue", "menuShortcut", "menuShortcutText", "menuSize", "menuSort",
    "menuText", "menuURL", "menuValue", "merge", "min", "mineActive", "mineDetectedBy",
    "missileState", "missileTarget", "missileTargetPos", "missionConfigFile",
    "missionDifficulty", "missionEnd", "missionName", "missionNameSource", "missionNamespace",
    "missionProfileNamespace", "missionStart", "missionVersion", "mod", "modelToWorld",
    "modelToWorldVisual", "modelToWorldVisualWorld", "modelToWorldWorld", "modParams",
    "moonIntensity", "moonPhase", "morale", "move", "move3DENCamera", "moveInAny",
    "moveInCargo", "moveInCommander", "moveInDriver", "moveInGunner", "moveInTurret",
    "moveObjectToEnd", "moveOut", "moveTarget", "moveTime", "moveTo", "moveToCompleted",
    "moveToFailed", "musicVolume",
    // N
    "name", "namedProperties", "nameSound", "nearEntities", "nearestBuilding",
    "nearestLocation", "nearestLocations", "nearestLocationWithDubbing", "nearestMines",
    "nearestObject", "nearestObjects", "nearestTerrainObjects", "nearObjects",
    "nearObjectsReady", "nearRoads", "nearSupplies", "nearTargets", "needReload",
    "needService", "netId", "netObjNull", "newOverlay", "nextMenuItemIndex",
    "nextWeatherChange", "nil", "nMenuItems", "not", "numberOfEnginesRTD", "numberToDate",
    // O
    "object", "objectCurators", "objectFromNetId", "objectParent", "objNull", "objStatus",
    "onBriefingGear", "onBriefingGroup", "onBriefingNotes", "onBriefingPlan",
    "onBriefingTeamSwitch", "onCommandModeChanged", "onDoubleClick", "onEachFrame",
    "onGroupIconClick", "onGroupIconOverEnter", "onGroupIconOverLeave",
    "onHCGroupSelectionChanged", "onMapSingleClick", "onPlayerConnected",
    "onPlayerDisconnected", "onPreloadFinished", "onPreloadStarted", "onShowNewObject",
    "onTeamSwitch", "openCuratorInterface", "openDLCPage", "openDSInterface", "openGPS",
    "openMap", "openSteamApp", "openYoutubeVideo", "opfor", "or", "orderGetIn", "overcast",
    "overcastForecast", "owner",
    // P
    "param", "params", "parentAttached", "parseNumber", "parseSimpleArray", "parseText",
    "parsingNamespace", "particlesQuality", "periscopeElevation", "pi", "pickWeaponPool",
    "pitch", "pixelGrid", "pixelGridBase", "pixelGridNoUIScale", "pixelH", "pixelW",
    "playableSlotsNumber", "playableUnits", "playAction", "playActionNow", "player",
    "playerRespawnTime", "playerSide", "playersNumber", "playerTargetLock", "playGesture",
    "playMission", "playMove", "playMoveNow", "playMusic", "playScriptedMission",
    "playSound", "playSound3D", "playSoundUI", "pose", "position", "positionCameraToWorld",
    "posScreenToWorld", "posWorldToScreen", "ppEffectAdjust", "ppEffectCommit",
    "ppEffectCommitted", "ppEffectCreate", "ppEffectDestroy", "ppEffectEnable",
    "ppEffectEnabled", "ppEffectForceInNVG", "precision", "preloadCamera", "preloadObject",
    "preloadSound", "preloadTitleObj", "preloadTitleRsc", "preprocessFile",
    "preprocessFileLineNumbers", "primaryWeapon", "primaryWeaponItems",
    "primaryWeaponMagazine", "priority", "private", "privateAll", "processDiaryLink",
    "processInitCommands", "productVersion", "profileName", "profileNamespace",
    "profileNameSteam", "progressLoadingScreen", "progressPosition", "progressSetPosition",
    "publicVariable", "publicVariableClient", "publicVariableServer", "pushBack",
    "pushBackUnique", "putWeaponPool", "pylonAction",
    // Q-R
    "queryItemsPool", "queryMagazinePool", "queryWeaponPool", "rad", "radioChannelAdd",
    "radioChannelCreate", "radioChannelInfo", "radioChannelRemove", "radioChannelSetCallSign",
    "radioChannelSetLabel", "radioEnabled", "radioVolume", "rain", "rainbow", "rainParams",
    "random", "rank", "rankId", "rating", "rectangular", "regexFind", "regexMatch",
    "regexReplace", "registeredTasks", "registerTask", "reload", "reloadEnabled",
    "remoteControl", "remoteControlled", "remoteExec", "remoteExecCall",
    "remoteExecutedJIPID", "remoteExecutedOwner", "remove3DENConnection",
    "remove3DENEventHandler", "remove3DENLayer", "removeAction", "removeAll3DENEventHandlers",
    "removeAllActions", "removeAllAssignedItems", "removeAllBinocularItems",
    "removeAllContainers", "removeAllCuratorAddons", "removeAllCuratorCameraAreas",
    "removeAllCuratorEditingAreas", "removeAllEventHandlers", "removeAllHandgunItems",
    "removeAllItems", "removeAllItemsWithMagazines", "removeAllMagazines",
    "removeAllMagazinesTurret", "removeAllMissionEventHandlers", "removeAllMPEventHandlers",
    "removeAllMusicEventHandlers", "removeAllOwnedMines", "removeAllPrimaryWeaponItems",
    "removeAllSecondaryWeaponItems", "removeAllUserActionEventHandlers", "removeAllWeapons",
    "removeBackpack", "removeBackpackGlobal", "removeBinocularItem", "removeClothing",
    "removeCuratorAddons", "removeCuratorCameraArea", "removeCuratorEditableObjects",
    "removeCuratorEditingArea", "removeDiaryRecord", "removeDiarySubject", "removeDrawIcon",
    "removeDrawLinks", "removeEventHandler", "removeFromRemainsCollector", "removeGoggles",
    "removeGroupIcon", "removeHandgunItem", "removeHeadgear", "removeItem",
    "removeItemFromBackpack", "removeItemFromUniform", "removeItemFromVest", "removeItems",
    "removeMagazine", "removeMagazineGlobal", "removeMagazines", "removeMagazinesTurret",
    "removeMagazineTurret", "removeMenuItem", "removeMissionEventHandler",
    "removeMPEventHandler", "removeMusicEventHandler", "removeOwnedMine",
    "removePrimaryWeaponItem", "removeSecondaryWeaponItem", "removeSimpleTask",
    "removeSwitchableUnit", "removeTeamMember", "removeUniform", "removeUserActionEventHandler",
    "removeVest", "removeWeapon", "removeWeaponAttachmentCargo", "removeWeaponCargo",
    "removeWeaponGlobal", "removeWeaponItem", "removeWeaponTurret", "reportRemoteTarget",
    "requiredVersion", "resetCamShake", "resetSubgroupDirection", "resistance", "resize",
    "resources", "respawnVehicle", "restartEditorCamera", "reveal", "revealMine", "reverse",
    "reversedMouseY", "roadAt", "roadsConnectedTo", "roleDescription", "ropeAttachedObjects",
    "ropeAttachedTo", "ropeAttachEnabled", "ropeAttachTo", "ropeCreate", "ropeCut",
    "ropeDestroy", "ropeDetach", "ropeEndPosition", "ropeLength", "ropes", "ropesAttachedTo",
    "ropeSegments", "ropeSetCargoMass", "ropeUnwind", "ropeUnwound", "rotorsForcesRTD",
    "rotorsRpmRTD", "round", "runInitScript",
    // S
    "safeZoneH", "safeZoneW", "safeZoneWAbs", "safeZoneX", "safeZoneXAbs", "safeZoneY",
    "save3DENInventory", "save3DENPreferences", "saveGame", "saveIdentity", "saveJoysticks",
    "saveMissionProfileNamespace", "saveOverlay", "saveProfileNamespace", "saveStatus",
    "saveVar", "savingEnabled", "say", "say2D", "say3D", "scopeName", "score", "scoreSide",
    "screenshot", "screenToWorld", "screenToWorldDirection", "scriptDone", "scriptName",
    "scriptNull", "scudState", "secondaryWeapon", "secondaryWeaponItems",
    "secondaryWeaponMagazine", "select", "selectBestPlaces", "selectDiarySubject",
    "selectedEditorObjects", "selectEditorObject", "selectionNames", "selectionPosition",
    "selectionVectorDirAndUp", "selectLeader", "selectMax", "selectMin", "selectNoPlayer",
    "selectPlayer", "selectRandom", "selectRandomWeighted", "selectThrowable", "selectWeapon",
    "selectWeaponTurret", "sendAUMessage", "sendSimpleCommand", "sendTask", "sendTaskResult",
    "sendUDPMessage", "sentencesEnabled", "serverCommand", "serverCommandAvailable",
    "serverCommandExecutable", "serverName", "serverNamespace", "serverTime", "set",
    "set3DENAttribute", "setAccTime", "setAirplaneThrottle", "setAirportSide", "setAmmo",
    "setAmmoCargo", "setAmmoOnPylon", "setAnimSpeedCoef", "setAperture", "setApertureNew",
    "setAttributes", "setAutonomous", "setBehaviour", "setBehaviourStrong",
    "setBleedingRemaining", "setCameraEffect", "setCameraInterest", "setCamShakeDefParams",
    "setCamShakeParams", "setCamUseTI", "setCaptive", "setCenterOfMass", "setCollisionLight",
    "setCombatBehaviour", "setCombatMode", "setConvoySeparation", "setCruiseControl",
    "setCuratorCameraAreaCeiling", "setCuratorCoef", "setCuratorEditingAreaType",
    "setCuratorSelected", "setCuratorWaypointCost", "setCurrentChannel", "setCurrentTask",
    "setCurrentWaypoint", "setCustomAimCoef", "setCustomSoundController", "setDamage",
    "setDammage", "setDate", "setDebriefingText", "setDefaultCamera", "setDestination",
    "setDetailMapBlendPars", "setDiaryRecordText", "setDiarySubjectPicture", "setDir",
    "setDirection", "setDrawIcon", "setDriveOnPath", "setDropInterval",
    "setDynamicSimulationDistance", "setDynamicSimulationDistanceCoef", "setEditorMode",
    "setEditorObjectScope", "setEffectCondition", "setEffectiveCommander", "setFace",
    "setFaceAnimation", "setFatigue", "setFeatureType", "setFlagAnimationPhase",
    "setFlagOwner", "setFlagSide", "setFlagTexture", "setFog", "setFormation",
    "setFormationTask", "setFormDir", "setFriend", "setFromEditor", "setFSMVariable",
    "setFuel", "setFuelCargo", "setFuelConsumptionCoef", "setGroupIcon", "setGroupIconParams",
    "setGroupIconsSelectable", "setGroupIconsVisible", "setGroupId", "setGroupIdGlobal",
    "setGroupOwner", "setGusts", "setHideBehind", "setHit", "setHitIndex",
    "setHitPointDamage", "setHorizonParallaxCoef", "setHUDMovementLevels", "setHumidity",
    "setIdentity", "setImportance", "setInfoPanel", "setLeader", "setLightAmbient",
    "setLightAttenuation", "setLightBrightness", "setLightColor", "setLightConePars",
    "setLightDayLight", "setLightFlareMaxDistance", "setLightFlareSize", "setLightIntensity",
    "setLightIR", "setLightnings", "setLightUseFlare", "setLightVolumeShape",
    "setLocalWindParams", "setMagazineTurretAmmo", "setMarkerAlpha", "setMarkerAlphaLocal",
    "setMarkerBrush", "setMarkerBrushLocal", "setMarkerColor", "setMarkerColorLocal",
    "setMarkerDir", "setMarkerDirLocal", "setMarkerDrawPriority", "setMarkerPolyline",
    "setMarkerPolylineLocal", "setMarkerPos", "setMarkerPosLocal", "setMarkerShadow",
    "setMarkerShadowLocal", "setMarkerShape", "setMarkerShapeLocal", "setMarkerSize",
    "setMarkerSizeLocal", "setMarkerText", "setMarkerTextLocal", "setMarkerType",
    "setMarkerTypeLocal", "setMass", "setMaxLoad", "setMimic", "setMissileTarget",
    "setMissileTargetPos", "setMissionOptions", "setMousePosition", "setMusicEffect",
    "setMusicEventHandler", "setName", "setNameSound", "setObjectArguments",
    "setObjectMaterial", "setObjectMaterialGlobal", "setObjectProxy", "setObjectScale",
    "setObjectTexture", "setObjectTextureGlobal", "setObjectViewDistance", "setOpticsMode",
    "setOvercast", "setOwner", "setOxygenRemaining", "setParticleCircle", "setParticleClass",
    "setParticleFire", "setParticleParams", "setParticleRandom", "setPhysicsCollisionFlag",
    "setPilotCameraDirection", "setPilotCameraOpticsMode", "setPilotCameraRotation",
    "setPilotCameraTarget", "setPilotLight", "setPiPEffect", "setPiPViewDistance",
    "setPitch", "setPlateNumber", "setPlayable", "setPlayerRespawnTime",
    "setPlayerVoNVolume", "setPos", "setPosASL", "setPosASL2", "setPosASLW", "setPosATL",
    "setPosition", "setPosWorld", "setPylonLoadout", "setPylonsPriority", "setRadioMsg",
    "setRain", "setRainbow", "setRandomLip", "setRank", "setRectangular", "setRepairCargo",
    "setShadowDistance", "setShotParents", "setSide", "setSimpleTaskAlwaysVisible",
    "setSimpleTaskCustomData", "setSimpleTaskDescription", "setSimpleTaskDestination",
    "setSimpleTaskTarget", "setSimpleTaskType", "setSimulWeatherLayers", "setSize",
    "setSkill", "setSlingLoad", "setSoundEffect", "setSpeaker", "setSpeech",
    "setSpeedMode", "setStamina", "setStaminaScheme", "setStatValue", "setSuppression",
    "setSystemOfUnits", "setTargetAge", "setTargetSize", "setTaskMarkerOffset",
    "setTaskResult", "setTaskState", "setTerrainGrid", "setTerrainHeight", "setText",
    "setTimeMultiplier", "setTIParameter", "setTitleEffect", "setToneMapping",
    "setToneMappingParams", "setTowParent", "setTrafficDensity", "setTrafficDistance",
    "setTrafficGap", "setTrafficSpeed", "setTriggerActivation", "setTriggerArea",
    "setTriggerInterval", "setTriggerStatements", "setTriggerText", "setTriggerTimeout",
    "setTriggerType", "setTurretLimits", "setTurretOpticsMode", "setType", "setUnconscious",
    "setUnitAbility", "setUnitCombatMode", "setUnitFreefallHeight", "setUnitLoadout",
    "setUnitPos", "setUnitPosWeak", "setUnitRank", "setUnitRecoilCoefficient",
    "setUnitTrait", "setUnloadInCombat", "setUserActionText", "setUserMFDText",
    "setUserMFDValue", "setVariable", "setVectorDir", "setVectorDirAndUp", "setVectorUp",
    "setVehicleAmmo", "setVehicleAmmoDef", "setVehicleArmor", "setVehicleCargo",
    "setVehicleId", "setVehicleInit", "setVehicleLock", "setVehiclePosition",
    "setVehicleRadar", "setVehicleReceiveRemoteTargets", "setVehicleReportOwnPosition",
    "setVehicleReportRemoteTargets", "setVehicleTIPars", "setVehicleVarName", "setVelocity",
    "setVelocityModelSpace", "setVelocityTransformation", "setViewDistance",
    "setVisibleIfTreeCollapsed", "setWaterFillPercentage", "setWaterLeakiness", "setWaves",
    "setWaypointBehaviour", "setWaypointCombatMode", "setWaypointCompletionRadius",
    "setWaypointDescription", "setWaypointForceBehaviour", "setWaypointFormation",
    "setWaypointHousePosition", "setWaypointLoiterAltitude", "setWaypointLoiterRadius",
    "setWaypointLoiterType", "setWaypointName", "setWaypointPosition", "setWaypointScript",
    "setWaypointSpeed", "setWaypointStatements", "setWaypointTimeout", "setWaypointType",
    "setWaypointVisible", "setWeaponReloadingTime", "setWeaponZeroing", "setWind",
    "setWindDir", "setWindForce", "setWindStr", "setWPPos", "show3DIcons", "showChat",
    "showCinemaBorder", "showCommandingMenu", "showCompass", "showCuratorCompass",
    "showGPS", "showHUD", "showLegend", "showMap", "shownAction", "shownArtilleryComputer",
    "shownChat", "shownCompass", "shownCuratorCompass", "showNewEditorObject", "shownGPS",
    "shownHUD", "shownMap", "shownPad", "shownRadio", "shownScoretable", "shownSubtitles",
    "shownUAVFeed", "shownWarrant", "shownWatch", "showPad", "showRadio", "showScoretable",
    "showSubtitles", "showUAVFeed", "showWarrant", "showWatch", "showWaypoint",
    "showWaypoints", "side", "sideAmbientLife", "sideChat", "sideEmpty", "sideEnemy",
    "sideFriendly", "sideLogic", "sideRadio", "sideUnknown", "simpleTasks",
    "simulationEnabled", "simulCloudDensity", "simulCloudOcclusion", "simulInClouds",
    "simulSetHumidity", "simulWeatherSync", "sin", "size", "sizeOf", "skill", "skillFinal",
    "skipTime", "sleep", "sliderPosition", "sliderRange", "sliderSetPosition",
    "sliderSetRange", "sliderSetSpeed", "sliderSpeed", "slingLoadAssistantShown",
    "soldierMagazines", "someAmmo", "sort", "soundParams", "soundVolume", "spawn",
    "speaker", "speechVolume", "speed", "speedMode", "splitString", "sqrt", "squadParams",
    "stance", "startLoadingScreen", "steamGameRecordingEvent", "step", "stop", "stopped",
    "stopSound", "str", "sunOrMoon", "supportInfo", "suppressFor", "surfaceIsWater",
    "surfaceNormal", "surfaceTexture", "surfaceType", "swimInDepth", "switch",
    "switchableUnits", "switchAction", "switchCamera", "switchGesture", "switchLight",
    "switchMove", "synchronizedObjects", "synchronizedTriggers", "synchronizedWaypoints",
    "synchronizeObjectsAdd", "synchronizeObjectsRemove", "synchronizeTrigger",
    "synchronizeWaypoint", "systemChat", "systemOfUnits", "systemTime", "systemTimeUTC",
    // T
    "tan", "targetKnowledge", "targets", "targetsAggregate", "targetsQuery",
    "taskAlwaysVisible", "taskChildren", "taskCompleted", "taskCustomData",
    "taskDescription", "taskDestination", "taskHint", "taskMarkerOffset", "taskName",
    "taskNull", "taskParent", "taskResult", "taskState", "taskType", "teamMember",
    "teamMemberNull", "teamName", "teams", "teamSwitch", "teamSwitchEnabled", "teamType",
    "terminate", "terrainIntersect", "terrainIntersectASL", "terrainIntersectAtASL",
    "text", "textLog", "textLogFormat", "tg", "then", "throw", "throwables", "time",
    "timeMultiplier", "titleCut", "titleFadeOut", "titleObj", "titleRsc", "titleText",
    "to", "toArray", "toFixed", "toJSON", "toLower", "toLowerANSI", "toString", "toUpper",
    "toUpperANSI", "triggerActivated", "triggerActivation", "triggerAmmo", "triggerArea",
    "triggerAttachedVehicle", "triggerAttachObject", "triggerAttachVehicle",
    "triggerDynamicSimulation", "triggerInterval", "triggerStatements", "triggerText",
    "triggerTimeout", "triggerTimeoutCurrent", "triggerType", "trim", "true", "try",
    "turretLocal", "turretOwner", "turretUnit", "tvAdd", "tvClear", "tvCollapse",
    "tvCollapseAll", "tvCount", "tvCurSel", "tvData", "tvDelete", "tvExpand", "tvExpandAll",
    "tvIsSelected", "tvPicture", "tvPictureRight", "tvSelection", "tvSetColor",
    "tvSetCurSel", "tvSetData", "tvSetPicture", "tvSetPictureColor",
    "tvSetPictureColorDisabled", "tvSetPictureColorSelected", "tvSetPictureRight",
    "tvSetPictureRightColor", "tvSetPictureRightColorDisabled",
    "tvSetPictureRightColorSelected", "tvSetSelectColor", "tvSetSelected", "tvSetText",
    "tvSetTooltip", "tvSetValue", "tvSort", "tvSortAll", "tvSortByValue", "tvSortByValueAll",
    "tvText", "tvTooltip", "tvValue", "type", "typeName", "typeOf",
    // U
    "UAVControl", "uiNamespace", "uiSleep", "uiTime", "unassignCurator", "unassignItem",
    "unassignTeam", "unassignVehicle", "underwater", "uniform", "uniformContainer",
    "uniformItems", "uniformMagazines", "uniqueUnitItems", "unitAddons", "unitAimPosition",
    "unitAimPositionVisual", "unitBackpack", "unitCombatMode", "unitIsUAV", "unitPos",
    "unitReady", "unitRecoilCoefficient", "units", "unitsBelowHeight", "unitTurret",
    "unlinkItem", "unlockAchievement", "unregisterTask", "updateDrawIcon", "updateMenuItem",
    "updateObjectTree", "useAIOperMapObstructionTest", "useAISteeringComponent",
    "useAudioTimeForMoves", "userInputDisabled",
    // V
    "values", "vectorAdd", "vectorCos", "vectorCrossProduct", "vectorDiff", "vectorDir",
    "vectorDirVisual", "vectorDistance", "vectorDistanceSqr", "vectorDotProduct",
    "vectorFromTo", "vectorLinearConversion", "vectorMagnitude", "vectorMagnitudeSqr",
    "vectorModelToWorld", "vectorModelToWorldVisual", "vectorMultiply", "vectorNormalized",
    "vectorSide", "vectorSideVisual", "vectorUp", "vectorUpVisual", "vectorWorldToModel",
    "vectorWorldToModelVisual", "vehicle", "vehicleCargoEnabled", "vehicleChat",
    "vehicleMoveInfo", "vehicleRadio", "vehicleReceiveRemoteTargets",
    "vehicleReportOwnPosition", "vehicleReportRemoteTargets", "vehicles", "vehicleVarName",
    "velocity", "velocityModelSpace", "verifySignature", "vest", "vestContainer",
    "vestItems", "vestMagazines", "viewDistance", "visibleCompass", "visibleGPS",
    "visibleMap", "visiblePosition", "visiblePositionASL", "visibleScoretable",
    "visibleWatch",
    // W-Z
    "waitUntil", "waterDamaged", "waves", "waypointAttachedObject", "waypointAttachedVehicle",
    "waypointAttachObject", "waypointAttachVehicle", "waypointBehaviour",
    "waypointCombatMode", "waypointCompletionRadius", "waypointDescription",
    "waypointForceBehaviour", "waypointFormation", "waypointHousePosition",
    "waypointLoiterAltitude", "waypointLoiterRadius", "waypointLoiterType", "waypointName",
    "waypointPosition", "waypoints", "waypointScript", "waypointsEnabledUAV",
    "waypointShow", "waypointSpeed", "waypointStatements", "waypointTimeout",
    "waypointTimeoutCurrent", "waypointType", "waypointVisible", "weaponAccessories",
    "weaponAccessoriesCargo", "weaponCargo", "weaponDirection", "weaponDisassemblyEnabled",
    "weaponInertia", "weaponLowered", "weaponReloadingTime", "weapons", "weaponsInfo",
    "weaponsItems", "weaponsItemsCargo", "weaponState", "weaponsTurret", "west",
    "WFSideText", "while", "wind", "windDir", "windRTD", "windStr", "wingsForcesRTD",
    "with", "worldName", "worldSize", "worldToModel", "worldToModelVisual", "worldToScreen",
];

// ── Control flow keywords (shown first in completions) ───────────────

const KEYWORDS = [
    "if", "then", "else", "while", "for", "do", "from", "to", "step",
    "switch", "case", "default", "try", "catch", "throw", "return",
    "private", "params", "call", "spawn", "spawnOn", "execVM", "exitWith",
    "forEach", "shared", "import", "freeze", "thaw",
];

const CONSTANTS = ["nil", "true", "false", "Nothing", "objNull", "grpNull",
    "controlNull", "displayNull", "scriptNull", "configNull", "taskNull",
    "west", "east", "resistance", "civilian", "independent",
];

// ── Helper: extract local variables from document ─────────────────────

function getLocalVariables(document: vscode.TextDocument): Set<string> {
    const locals = new Set<string>();
    const text = document.getText();
    const re = /\b(_[a-zA-Z_][a-zA-Z0-9_]*)\b/g;
    let m: RegExpExecArray | null;
    while ((m = re.exec(text)) !== null) {
        locals.add(m[1]);
    }
    return locals;
}

// ── Completion provider ───────────────────────────────────────────────

export class SqfCompletionProvider implements vscode.CompletionItemProvider {

    provideCompletionItems(
        document: vscode.TextDocument,
        position: vscode.Position,
    ): vscode.CompletionItem[] {
        const linePrefix = document.lineAt(position).text.substring(0, position.character);
        const items: vscode.CompletionItem[] = [];

        // ── Keywords ──
        for (const kw of KEYWORDS) {
            const item = new vscode.CompletionItem(kw, vscode.CompletionItemKind.Keyword);
            item.sortText = '0_' + kw;
            items.push(item);
        }

        // ── Constants ──
        for (const c of CONSTANTS) {
            const item = new vscode.CompletionItem(c, vscode.CompletionItemKind.Constant);
            item.sortText = '1_' + c;
            items.push(item);
        }

        // ── Commands (all 2630) ──
        for (const cmd of COMMANDS) {
            const item = new vscode.CompletionItem(cmd, vscode.CompletionItemKind.Function);
            item.sortText = '2_' + cmd;
            items.push(item);
        }

        // ── Local variables from document ──
        for (const v of getLocalVariables(document)) {
            const item = new vscode.CompletionItem(v, vscode.CompletionItemKind.Variable);
            item.sortText = '3_' + v;
            items.push(item);
        }

        return items;
    }
}
